services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USERNAME: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
